apiVersion: v1
kind: Pod
metadata:
  name: mylivenessprobe
spec:
  containers:
  - name: liveness
    image: httpd
    ports:
      - containerPort: 80
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      timeoutSeconds: 30
      httpGet:
        path : /
        port: 80
