apiVersion: v1
kind: PersistentVolume
metadata:
  name: testvol
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-02c05da8cf9a75ac9
    fsType: ext4
