
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testvol-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""  # or specify a StorageClass name if exists
  selector:
    matchLabels:
      type: local
