apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Ashok; sleep 5; done"]
      env:
        - name: Name
          value: ashokChandraReddy
        - name: Degination
          value: SRE2
  restartPolicy: Never
