apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Ashok; sleep 25; done"]
    - name: c01
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo bye-Ashok; sleep 50; done"]

  restartPolicy: Never
