apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
spec:
  limits:
  - type: Container
    max:
      cpu: "2"
      memory: "1Gi"
      ephemeral-storage: "2Gi"
      storage: "5Gi"
    min:
      cpu: "0.1"
      memory: "50Mi"
    default:
      cpu: "0.5"
      memory: "200Mi"
  - type: Pod
    max:
      pods: "10"
  - type: PersistentVolumeClaim
    max:
      storage: "10Gi"
