apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: <your-namespace-name>
spec:
  limits:
  - type: Container
    max:
      cpu: "2"
      memory: "1Gi"
    min:
      cpu: "0.1"
      memory: "50Mi"
    default:
      cpu: "0.5"
      memory: "200Mi"
  - type: PersistentVolumeClaim
    max:
      storage: "1Gi"
    min:
      storage: "1Mi"
    default:
      storage: "200Mi"
